message = input("Please type your message here: ")
person = input("Please type the name of the person you wish to send your message to: ")
message_sender = input("Please type your name here: ")
print(f"This is a message from {message_sender}")
print("______________________________")
print(f"For the attention of {person}: {message} ")
